#!/usr/bin/python3
import sys
import math

def factorize(n):
    if n % 2 == 0:
        return("{} = {} * {}".format(n, 2, (n // 2)))
    
    sq = math.sqrt(n)
    """
    if sq % 1 == 0:
        return("{} = {} * {}".format(n, sq, sq)) 

    else:"""
    for i in range(3, int(sq) + 1, 2):
        if n % i == 0:
            return("{} = {} * {}".format(n, i, (n // i)))
        if n % (sq + i) == 0:
            return("{} = {} * {}".format(n, (n // (sq + i)),sq + i))
        if n % (sq - i) == 0:
            return("{} = {} * {}".format(n, (n // (sq - i)),sq - i))
        else:
            return("{} = {} * {}".format(n, 1, n))

if __name__ == '__main__':
        with open(sys.argv[1], encoding="utf-8") as my_file:
            for i in my_file.readlines():
                print(factorize(int(i)))
        
